import { Task } from "../types";

export const mockTasks: Task[] = [
    {
        id: 1,
        code: "NET-001",
        name: "Router Configuration",
        area: "Networking",
        description: "Configure and update routing tables on the core switch to optimize internal traffic flow.",
        CreatedAt: "2026-01-10",
    },
    {
        id: 2,
        code: "NET-002",
        name: "VPN Tunnel Setup",
        area: "Networking",
        description: "Establish a site-to-site VPN tunnel between the main office and the remote branch.",
        CreatedAt: "2026-01-15",
    },
    {
        id: 3,
        code: "NET-003",
        name: "Firewall Rules Review",
        area: "Networking",
        description: "Audit and update inbound/outbound firewall rules to align with current security policies.",
        CreatedAt: "2026-01-22",
    },
    {
        id: 4,
        code: "HW-001",
        name: "Workstation RAM Upgrade",
        area: "Hardware",
        description: "Replace 8 GB RAM modules with 16 GB on developer workstations to improve performance.",
        CreatedAt: "2026-02-03",
    },
    {
        id: 5,
        code: "HW-002",
        name: "Server Disk Replacement",
        area: "Hardware",
        description: "Replace failing HDD on the backup server with a new SSD and restore data from the last backup.",
        CreatedAt: "2026-02-11",
    },
    {
        id: 6,
        code: "HW-003",
        name: "UPS Battery Maintenance",
        area: "Hardware",
        description: "Test and replace aging UPS batteries in the server room to ensure uninterrupted power supply.",
        CreatedAt: "2026-02-18",
    },
    {
        id: 7,
        code: "SW-001",
        name: "OS Patch Deployment",
        area: "Software",
        description: "Deploy the latest security patches to all Windows workstations across the organization.",
        CreatedAt: "2026-03-01",
    },
    {
        id: 8,
        code: "SW-002",
        name: "ERP System Update",
        area: "Software",
        description: "Upgrade the ERP platform to version 4.2 and run post-update validation tests.",
        CreatedAt: "2026-03-08",
    },
    {
        id: 9,
        code: "SW-003",
        name: "Antivirus Policy Rollout",
        area: "Software",
        description: "Deploy updated antivirus definitions and enforce new scanning policies via Group Policy.",
        CreatedAt: "2026-03-14",
    },
];
